import baseConfig from "./base.mjs";

export default {
  extends: baseConfig,
  plugins: ["stylelint-order"],
  rules: {
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "block-no-empty": null,
    "color-hex-length": "short",
    "selector-class-pattern": null,
    "property-no-vendor-prefix": true,
    "value-no-vendor-prefix": true,
    "selector-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "at-rule-no-vendor-prefix": true,
    "selector-max-specificity": "0,4,1",
    "declaration-no-important": true,
    "color-function-notation": null,
    "length-zero-no-unit": null,
    "no-descending-specificity": null,
    "selector-pseudo-element-colon-notation": null,
    "selector-pseudo-element-no-unknown": null,
    "shorthand-property-no-redundant-values": null,
    "unit-allowed-list": [
      "%",
      "deg",
      "em",
      "px",
      "rem",
      "pc",
      "s",
      "vh",
      "fr",
      "svh",
      "dvh",
      "lvh",
      "vw",
      "svw",
      "dvw",
      "lvw",
      "vmax",
      "vmin",
      "cqw",
      "cqh",
      "cqi",
      "cqb",
      "cqmin",
      "cqmax",
    ],
    "order/properties-alphabetical-order": null,
    "order/properties-order": [
      [
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",
        "display",
        "flex",
        "flex-direction",
        "flex-wrap",
        "justify-content",
        "align-items",
        "align-content",
        "gap",
        "visibility",
        "overflow",
        "box-sizing",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "border",
        "border-width",
        "border-style",
        "border-color",
        "border-top",
        "border-top-width",
        "border-top-style",
        "border-top-color",
        "border-right",
        "border-right-width",
        "border-right-style",
        "border-right-color",
        "border-bottom",
        "border-bottom-width",
        "border-bottom-style",
        "border-bottom-color",
        "border-left",
        "border-left-width",
        "border-left-style",
        "border-left-color",
        "border-radius",
        "opacity",
        "color",
        "font",
        "font-family",
        "font-size",
        "font-weight",
        "line-height",
        "text-align",
        "text-decoration",
        "letter-spacing",
        "word-spacing",
        "list-style",
        "background",
        "background-color",
        "background-image",
        "background-position",
        "background-repeat",
        "background-size",
        "box-shadow",
        "text-shadow",
        "transition",
        "animation",
        "appearance",
        "content",
        "cursor",
      ],
      { unspecified: "ignore" },
    ],
  },
};
